modLoader="lowcodefml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/PaintNinja/Anacondy/issues"

[[mods]]
modId="anacondymod"
version="0.3.0-alpha"
displayName="Anacondy"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/anacondy"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
credits="Thanks to FalsePattern for helping fix some edge-cases relating to early resolving of CONDYs before their backing fields are set. Thanks to LexManos for helping me get both the transformer and mod working in the same jar."
authors="Paint_Ninja"
displayTest="IGNORE_ALL_VERSION"

description='''Straighten those snakes!

Anacondy is an optimisation mod that rewrites accesses of effectively immutable fields in various parts of the game to
use CONDY (CONSTANT_Dynamic) instructions, allowing Java to more confidently perform constant folding optimisations.

In other words, Anacondy gives Java stronger guarantees that certain things never change after the game has started,
allowing the Java runtime to better optimise everything that touches those things and to do it sooner, which improves
performance.

This is an early alpha version. Efforts have been made to ensure mod compatibility and stability, however it lacks
real-world testing. Please report any issues you find on the issue tracker.
'''

[[dependencies.anacondymod]]
    modId="forge"
    mandatory=true
    versionRange="[60,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.anacondymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"
